name = "MCubed"
author = "ascent_08"
version = "a0.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5906e997fa94365e252d4a2053c4588c335dd53f89d0dff683c1b290df610e0"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
