name = "MCubed"
author = "ascent_08"
version = "a0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "726266c4dcc73cbaf6b9b30f610a8b16b43b93689d2a3fd345631f1dfe9e50e1"

[versions]
fabric = "0.13.2"
minecraft = "1.18.2"
