name = "MCubed"
author = "ascent_08"
version = "a0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14b255ef2082b8fcfd222271e1e3b27eaec248ee041f38ba0c210eda0c6dca33"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
