name = "MCubed"
author = "ascent_"
version = "a0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58b9d45aee1e89a5365087978f6c1fffb0f89b21a424d19f7ea655cc3be951d0"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
