name = "MCubed"
author = "ascent_08"
version = "a0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f6c6dd41a7f420316aeb5364692536e97d19cc49f3c4da99dcd02a2ecf95005"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
