name = "MCubed"
author = "ascent_"
version = "a0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbcc67265e9f781f38f57ef644e66abc2075f8bfde36d7c0954feb4a6f08e21d"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
