name = "MCubed"
author = "ascent_08"
version = "a0.0.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70f41558cab91afdffa1921cdd04eb8e345917e68ecf19b1953b2bedd08d6327"

[versions]
fabric = "0.13.2"
minecraft = "1.18.2"
