name = "MCubed"
author = "ascent_"
version = "a0.0.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd45275e47b28f7b6a76c95d07a2a0b3074604c078e5fc26d9cbbebee8120024"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
