name = "MCubed"
author = "ascent_08"
version = "a0.0.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8a705de6394ee5494d82247ba55a4f67640b5ea77089e250bfb8b9a2d6d1b95"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
