name = "MCubed"
author = "ascent_"
version = "a0.0.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbc8b676a21e5a387e9ee0f8d82ac9add91cbe463221bbb3a1a32069a8fd7c5d"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
