name = "MCubed"
author = "ascent_"
version = "a0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f50edeaa82d49430cd181e3aa855906964cb11bc50bf0a7540526a2c1f37485"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
