name = "MCubed"
author = "ascent_08"
version = "a0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bcfaea6bd1a7e137ae0facdb069fb5c54efd7542bba9d739d8a729292b0c765"

[versions]
fabric = "0.13.2"
minecraft = "1.18.2"
