name = "MCubed"
author = "ascent_08"
version = "a0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62f4a2d53c377ba97a329f65dca41a76591ebe7c062d8a568365e8770a24eef5"

[versions]
fabric = "0.13.2"
minecraft = "1.18.2"
