name = "MCubed"
author = "ascent_08"
version = "a0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3996e8dd6d36c4694d374740fb44ecd60e1696668ab4fd15cbc408244537f10a"

[versions]
fabric = "0.13.2"
minecraft = "1.18.2"
