name = "MCubed"
author = "ascent_08"
version = "a0.0.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d10f6a6abd0c547d4257d97a63ef2e85544445dc01202830387d58acc533419"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
