name = "MCubed"
author = "ascent_08"
version = "a0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bd6091b31b36e5bc8db69ca85d76d39ea71104d31146052b6c188492b018eb0"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
