name = "MCubed"
author = "ascent_08"
version = "a0.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c154ffee62410bfe062d488aa4ad4c19200378bb596e6d00af5b6c33ce9a9a03"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
