name = "MCubed"
author = "ascent_08"
version = "a0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "629b45393d07f5ae109fb089bfc697274e3bdf9b2daf669e93e5389439096ec8"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
