name = "MCubed"
author = "ascent_08"
version = "a0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f32c09e6d095abdfbaac755ac631c688afb88e44b9dd23da319ef9ef1dc4f1e"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
