name = "Architectury API (Fabric)"
filename = "architectury-4.1.41.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3742/42/architectury-4.1.41.jar"
hash-format = "sha1"
hash = "efa0fd36e3f00d1ee4eb356e8b352fb82c20e970"

[update]
[update.curseforge]
file-id = 3742042
project-id = 419697
