name = "Architectury API (Fabric)"
filename = "architectury-4.0.30.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/589/architectury-4.0.30.jar"
hash-format = "murmur2"
hash = "1967854808"

[update]
[update.curseforge]
file-id = 3671589
project-id = 419697
