name = "Architectury API (Fabric)"
filename = "architectury-4.2.49.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/527/architectury-4.2.49.jar"
hash-format = "sha1"
hash = "f3832f7ca9dba38a6832cf36d35b59f425ac4da2"

[update]
[update.curseforge]
file-id = 3755527
project-id = 419697
