name = "BCLib"
filename = "bclib-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3707/407/bclib-1.4.0.jar"
hash-format = "sha1"
hash = "7c5f8c131f6d05fb3073cf3869240c6e59182d5a"

[update]
[update.curseforge]
file-id = 3707407
project-id = 495191
