name = "BCLib"
filename = "bclib-1.4.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3740/507/bclib-1.4.3.jar"
hash-format = "sha1"
hash = "a53ab501e38af431078682459ea6164069ec4027"

[update]
[update.curseforge]
file-id = 3740507
project-id = 495191
