name = "BCLib"
filename = "bclib-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3650/880/bclib-1.3.4.jar"
hash-format = "murmur2"
hash = "2653865438"

[update]
[update.curseforge]
file-id = 3650880
project-id = 495191
