name = "Blockus"
filename = "blockus-2.4.5+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3766/42/blockus-2.4.5+1.18.2.jar"
hash-format = "sha1"
hash = "32b2bae0fde53b0e766e9bd2e511b2f32a8bfebb"

[update]
[update.curseforge]
file-id = 3766042
project-id = 312289
