name = "Blockus"
filename = "blockus-2.3.6+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/94/blockus-2.3.6+1.18.1.jar"
hash-format = "murmur2"
hash = "3491340637"

[update]
[update.curseforge]
file-id = 3670094
project-id = 312289
