name = "Blockus"
filename = "blockus-2.4.4+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/903/blockus-2.4.4+1.18.2.jar"
hash-format = "sha1"
hash = "c4525a0034e6d2d383fd36f79bc28b52358db559"

[update]
[update.curseforge]
file-id = 3755903
project-id = 312289
