name = "Blockus"
filename = "blockus-2.3.5+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/473/blockus-2.3.5+1.18.1.jar"
hash-format = "murmur2"
hash = "2243100941"

[update]
[update.curseforge]
file-id = 3668473
project-id = 312289
