name = "Botania (Fabric)"
filename = "Botania-1.18.2-433-FABRIC.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "85eb5c53d0694d45e95d59ca56e1eda6964de6de"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3818544
project-id = 421839
