name = "Botania (Fabric)"
filename = "Botania-1.18.1-429-FABRIC.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3664/221/Botania-1.18.1-429-FABRIC.jar"
hash-format = "murmur2"
hash = "3310930053"

[update]
[update.curseforge]
file-id = 3664221
project-id = 421839
