name = "Controlling"
filename = "Controlling-fabric-1.18.2-9.0+16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/327/Controlling-fabric-1.18.2-9.0+16.jar"
hash-format = "murmur2"
hash = "1023785231"

[update]
[update.curseforge]
file-id = 3669327
project-id = 250398
