name = "Chisel Refabricated"
filename = "chisel-1.4.5+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/994/chisel-1.4.5+1.18.2.jar"
hash-format = "sha1"
hash = "dbfe534e98eba05972e86c839108279cdc339cb2"

[update]
[update.curseforge]
file-id = 3672994
project-id = 551763
