name = "Fabric API"
filename = "fabric-api-0.47.8+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3660/981/fabric-api-0.47.8+1.18.2.jar"
hash-format = "murmur2"
hash = "376795421"

[update]
[update.curseforge]
file-id = 3660981
project-id = 306612
