name = "Fabric API"
filename = "fabric-api-0.47.9+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/153/fabric-api-0.47.9+1.18.2.jar"
hash-format = "murmur2"
hash = "1552428024"

[update]
[update.curseforge]
file-id = 3671153
project-id = 306612
