name = "Feature NBT Deadlock Be Gone"
filename = "feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3665/605/feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar"
hash-format = "murmur2"
hash = "2482958392"

[update]
[update.curseforge]
file-id = 3665605
project-id = 560323
