name = "FerriteCore (Fabric)"
filename = "ferritecore-4.2.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/143/ferritecore-4.2.0-fabric.jar"
hash-format = "murmur2"
hash = "3471839646"

[update]
[update.curseforge]
file-id = 3672143
project-id = 459857
