name = "FTB Chunks (Fabric)"
filename = "ftb-chunks-fabric-1802.3.5-build.130.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/653/ftb-chunks-fabric-1802.3.5-build.130.jar"
hash-format = "sha1"
hash = "c820ea7177aa0b8e434ad2e89b04ddfc6149d904"

[update]
[update.curseforge]
file-id = 3725653
project-id = 472657
