name = "GeckoLib"
filename = "geckolib-fabric-1.18-3.0.35.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/587/geckolib-fabric-1.18-3.0.35.jar"
hash-format = "murmur2"
hash = "1580230845"

[update]
[update.curseforge]
file-id = 3667587
project-id = 388172
