name = "Hookshot"
filename = "hookshot-r24.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3626/207/hookshot-r24.jar"
hash-format = "murmur2"
hash = "1965801082"

[update]
[update.curseforge]
file-id = 3626207
project-id = 396512
