name = "Hookshot"
filename = "hookshot-r25.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/184/hookshot-r25.jar"
hash-format = "murmur2"
hash = "346086107"

[update]
[update.curseforge]
file-id = 3668184
project-id = 396512
