name = "Inmis"
filename = "inmis-2.5.2-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3704/532/inmis-2.5.2-1.18.2.jar"
hash-format = "sha1"
hash = "292894adeb423806731b01f01a079841d055800e"

[update]
[update.curseforge]
file-id = 3704532
project-id = 369254
