name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3658/506/InventoryProfilesNext-fabric-1.18-1.3.4.jar"
hash-format = "murmur2"
hash = "393103342"

[update]
[update.curseforge]
file-id = 3658506
project-id = 495267
