name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18-1.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3653/51/InventoryProfilesNext-fabric-1.18-1.3.3.jar"
hash-format = "murmur2"
hash = "2946933406"

[update]
[update.curseforge]
file-id = 3653051
project-id = 495267
