name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18.2-1.3.4-BETA+Cbc699f4-SNAPSHOT.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/860/InventoryProfilesNext-fabric-1.18.2-1.3.4-BETA+Cbc699f4-SNAPSHOT.jar"
hash-format = "murmur2"
hash = "4221755988"

[update]
[update.curseforge]
file-id = 3669860
project-id = 495267
