name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18.2-1.4.0.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "e64426b95a2997ea4e6a31884401697a2040b888"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3800837
project-id = 495267
