name = "Item Filters (Fabric)"
filename = "item-filters-fabric-1802.2.7-build.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/878/item-filters-fabric-1802.2.7-build.18.jar"
hash-format = "sha1"
hash = "838bff933667603d0bffff63da3b350de32afd3b"

[update]
[update.curseforge]
file-id = 3725878
project-id = 438500
