name = "JourneyMap"
filename = "journeymap-1.18.2-5.8.4-fabric.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "deba35f4e533ee4231f7378a2eea2b3665598679"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3796377
project-id = 32274
