name = "Kibe Utilities"
filename = "kibe-1.9.7-BETA+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/408/kibe-1.9.7-BETA+1.18.jar"
hash-format = "murmur2"
hash = "834935020"

[update]
[update.curseforge]
file-id = 3671408
project-id = 388832
