name = "Kibe Utilities"
filename = "kibe-1.9.5-BETA+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/194/kibe-1.9.5-BETA+1.18.jar"
hash-format = "murmur2"
hash = "402879095"

[update]
[update.curseforge]
file-id = 3667194
project-id = 388832
