name = "Lithium (Fabric)"
filename = "lithium-fabric-mc1.18.2-0.7.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/312/lithium-fabric-mc1.18.2-0.7.9.jar"
hash-format = "murmur2"
hash = "2854996048"

[update]
[update.curseforge]
file-id = 3670312
project-id = 360438
