name = "Mod Menu"
filename = "modmenu-3.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/801/modmenu-3.1.0.jar"
hash-format = "murmur2"
hash = "2833884656"

[update]
[update.curseforge]
file-id = 3668801
project-id = 308702
