name = "Oh The Biomes You'll Go Refabricated"
filename = "Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3712/141/Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-7.jar"
hash-format = "sha1"
hash = "3201a9e2ac8ca69b7454266abdda0643f9402bb8"

[update]
[update.curseforge]
file-id = 3712141
project-id = 391378
