name = "Oh The Biomes You'll Go Refabricated"
filename = "Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3695/54/Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-3.jar"
hash-format = "sha1"
hash = "41a5f6eb7f72677374303c6fc04b4452a597df8d"

[update]
[update.curseforge]
file-id = 3695054
project-id = 391378
