name = "oÏ‰o (owo-lib)"
filename = "owo-lib-0.6.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3708/655/owo-lib-0.6.0+1.18.jar"
hash-format = "sha1"
hash = "b3a07429257c236ccde11d0f14ea635ade270e94"

[update]
[update.curseforge]
file-id = 3708655
project-id = 532610
