name = "oÏ‰o (owo-lib)"
filename = "owo-lib-0.5.4+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/499/owo-lib-0.5.4+1.18.jar"
hash-format = "murmur2"
hash = "837073585"

[update]
[update.curseforge]
file-id = 3667499
project-id = 532610
