name = "oÏ‰o (owo-lib)"
filename = "owo-lib-0.7.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3760/611/owo-lib-0.7.0+1.18.jar"
hash-format = "sha1"
hash = "cef12ddbc4c9817e0fd9843be14418f0195df76c"

[update]
[update.curseforge]
file-id = 3760611
project-id = 532610
