name = "Reborn Core"
filename = "RebornCore-5.2.0-beta.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/448/RebornCore-5.2.0-beta.2.jar"
hash-format = "murmur2"
hash = "2785660716"

[update]
[update.curseforge]
file-id = 3672448
project-id = 237903
