name = "Reborn Core"
filename = "RebornCore-5.2.0-beta.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3761/10/RebornCore-5.2.0-beta.3.jar"
hash-format = "sha1"
hash = "973db7681c4f8615511927036b7f06ba7c399736"

[update]
[update.curseforge]
file-id = 3761010
project-id = 237903
