name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures_fabric-4.1.5+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/642/repurposed_structures_fabric-4.1.5+1.18.2.jar"
hash-format = "sha1"
hash = "a9c0c083bc42d5cecb7e2de78db4b771df5d5171"

[update]
[update.curseforge]
file-id = 3755642
project-id = 391366
