name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures_fabric-4.1.0+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3729/850/repurposed_structures_fabric-4.1.0+1.18.2.jar"
hash-format = "sha1"
hash = "cf2ff072fa5b29dd9ae77c6c05f482da2e586e4c"

[update]
[update.curseforge]
file-id = 3729850
project-id = 391366
