name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures_fabric-4.1.1+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3735/592/repurposed_structures_fabric-4.1.1+1.18.2.jar"
hash-format = "sha1"
hash = "06d98d88f690b568ac48550c970536a5d39ae07f"

[update]
[update.curseforge]
file-id = 3735592
project-id = 391366
