name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures_fabric-4.0.0+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/39/repurposed_structures_fabric-4.0.0+1.18.2.jar"
hash-format = "murmur2"
hash = "78023568"

[update]
[update.curseforge]
file-id = 3669039
project-id = 391366
