name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures_fabric-4.1.9+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "8afda55dc7faa470d1bafe646bb7ca342f4711ed"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3803918
project-id = 391366
