name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-8.0.438.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/977/RoughlyEnoughItems-8.0.438.jar"
hash-format = "murmur2"
hash = "2864139584"

[update]
[update.curseforge]
file-id = 3666977
project-id = 310111
