name = "Sodium"
filename = "sodium-fabric-mc1.18.2-0.4.1+build.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/187/sodium-fabric-mc1.18.2-0.4.1+build.15.jar"
hash-format = "murmur2"
hash = "415818115"

[update]
[update.curseforge]
file-id = 3669187
project-id = 394468
