name = "Spectrum"
filename = "spectrum-1.3.1-1.18.2-midgame16-trinkets-brewing.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3750/375/spectrum-1.3.1-1.18.2-midgame16-trinkets-brewing.jar"
hash-format = "sha1"
hash = "7152aadfeefab31b0278467bd1288c731e9db63f"

[update]
[update.curseforge]
file-id = 3750375
project-id = 556967
