name = "Spectrum"
filename = "spectrum-1.3.3-1.18.2-midgame18-trinkets-brewing.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3761/257/spectrum-1.3.3-1.18.2-midgame18-trinkets-brewing.jar"
hash-format = "sha1"
hash = "30b7a871a26cb54a4899addb95806c3006042102"

[update]
[update.curseforge]
file-id = 3761257
project-id = 556967
