name = "Starlight (Fabric)"
filename = "starlight-1.0.2+fabric.89b8d9f.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/443/starlight-1.0.2+fabric.89b8d9f.jar"
hash-format = "murmur2"
hash = "2297769584"

[update]
[update.curseforge]
file-id = 3667443
project-id = 521783
