name = "Tech Reborn"
filename = "TechReborn-5.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3663/41/TechReborn-5.1.0.jar"
hash-format = "murmur2"
hash = "526092373"

[update]
[update.curseforge]
file-id = 3663041
project-id = 233564
