name = "Tech Reborn"
filename = "TechReborn-5.2.0-beta.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/447/TechReborn-5.2.0-beta.2.jar"
hash-format = "murmur2"
hash = "2938801108"

[update]
[update.curseforge]
file-id = 3672447
project-id = 233564
