name = "TerraBlender (Fabric)"
filename = "TerraBlender-fabric-1.18.2-1.1.0.98.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3723/886/TerraBlender-fabric-1.18.2-1.1.0.98.jar"
hash-format = "sha1"
hash = "da08d6c52c1e8c76d19f424536dd5e2c50d81862"

[update]
[update.curseforge]
file-id = 3723886
project-id = 565956
