name = "TerraBlender (Fabric)"
filename = "TerraBlender-fabric-1.18.2-1.1.0.93.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3684/312/TerraBlender-fabric-1.18.2-1.1.0.93.jar"
hash-format = "sha1"
hash = "2aed5c49da52c50f88115df42f2be16ae9c99435"

[update]
[update.curseforge]
file-id = 3684312
project-id = 565956
