name = "Trinkets (Fabric)"
filename = "trinkets-3.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/842/trinkets-3.3.0.jar"
hash-format = "murmur2"
hash = "2066444158"

[update]
[update.curseforge]
file-id = 3669842
project-id = 341284
