name = "WTHIT"
filename = "wthit-fabric-4.5.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3654/879/wthit-fabric-4.5.2.jar"
hash-format = "murmur2"
hash = "1107237399"

[update]
[update.curseforge]
file-id = 3654879
project-id = 440979
