name = "WTHIT"
filename = "wthit-fabric-4.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3662/941/wthit-fabric-4.7.0.jar"
hash-format = "murmur2"
hash = "788830066"

[update]
[update.curseforge]
file-id = 3662941
project-id = 440979
