name = "WTHIT"
filename = "wthit-fabric-4.9.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3765/902/wthit-fabric-4.9.0.jar"
hash-format = "sha1"
hash = "f8dae0ed10abcbfc105efc3478f19101ba1d1f26"

[update]
[update.curseforge]
file-id = 3765902
project-id = 440979
