name = "WTHIT"
filename = "wthit-fabric-4.7.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/571/wthit-fabric-4.7.2.jar"
hash-format = "murmur2"
hash = "729823864"

[update]
[update.curseforge]
file-id = 3669571
project-id = 440979
