name = "WTHIT"
filename = "wthit-fabric-4.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/962/wthit-fabric-4.7.1.jar"
hash-format = "murmur2"
hash = "4024678544"

[update]
[update.curseforge]
file-id = 3667962
project-id = 440979
