name = "You're in Grave Danger"
filename = "youre-in-grave-danger-1.2.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3645/91/youre-in-grave-danger-1.2.18.jar"
hash-format = "murmur2"
hash = "4140409062"

[update]
[update.curseforge]
file-id = 3645091
project-id = 544912
