name = "You're in Grave Danger"
filename = "youre-in-grave-danger-1.3.5.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "dc403bc87793ec7a10341d6bfe5835b7d8658ade"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3791555
project-id = 544912
