name = "You're in Grave Danger"
filename = "youre-in-grave-danger-1.2.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/12/youre-in-grave-danger-1.2.21.jar"
hash-format = "murmur2"
hash = "4017145771"

[update]
[update.curseforge]
file-id = 3670012
project-id = 544912
