name = "You're in Grave Danger"
filename = "youre-in-grave-danger-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/15/youre-in-grave-danger-1.3.0.jar"
hash-format = "murmur2"
hash = "3625104368"

[update]
[update.curseforge]
file-id = 3670015
project-id = 544912
