name = "You're in Grave Danger"
filename = "youre-in-grave-danger-1.2.19.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3657/292/youre-in-grave-danger-1.2.19.jar"
hash-format = "murmur2"
hash = "1978471796"

[update]
[update.curseforge]
file-id = 3657292
project-id = 544912
