name = "YUNG's Better Strongholds (Fabric)"
filename = "BetterStrongholds-Fabric-1.18.1-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3650/507/BetterStrongholds-Fabric-1.18.1-1.0.1.jar"
hash-format = "murmur2"
hash = "2716165991"

[update]
[update.curseforge]
file-id = 3650507
project-id = 480684
